### ISSUE TITLE
OACTools jsonschema is invalid

### ISSUE THREAD

**Issue by bradschwartz** [openautocomplete/oactool#1]
On a fresh install of oactool the produced JSON OAC Schema of the tool itself has validation errors.

Steps to reproduce:

```bash
$ pip install oactool
$ oactool jsonschema > oacschema.json
$ oactool validate oacschema.json
[oacschema.json] 3 validation errors for Specification
openautocompletion
  field required (type=value_error.missing)
components
  field required (type=value_error.missing)
cli
  field required (type=value_error.missing)
```

Haven't actually checked if the validator is incorrect or the schema is.

**Comment by GamePad64** [comment]
`oactool jsonschema` outputs a document in JSON Schema format, that could be used to validate OAC documents for correctness in other applications.
`oactool validate` does not accept JSON Schema document as an input. It accepts an OAC document, which could be found [here](https://github.com/openautocomplete/completions/tree/master/completions), for example.

**Comment by bradschwartz** [comment]
Ah yeah I see that now, thanks!
